#!/bin/bash

ID=$(id -u)

validate(){

    if [ $1 -ne 0 ]
    then 
        echo "ERROR"
        exit 1
    else
        echo " $2 is successful"
    fi

}

if [ $ID -ne 0 ]
then 
    echo "ERROR : You are a root user"
    exit 1
else
    echo "you are root user"
fi

#yum install nginx -y

echo "cool"

#validate $? installation_of_nginx

echo $# $@ $0





 