#!/bin/bash

ID=$(id -u)

TIMESTAMP=$(date +%F-%H-%M)

LOG_FILE="/tmp/$0-$TIMESTAMP"

validate(){

    if [ $1 -ne 0 ]
    then 
        echo "ERROR"
        exit 1
    else
        echo " $2 is successful"
    fi

}

if [ $ID -ne 0 ]
then 
    echo "ERROR : You are a root user"
    exit 1
else
    echo "you are root user"
fi

yum install mysql -y &>> $LOG_FILE

validate $? installation_of_nginx





 