#!/bin/bash

ID=$(id -u)

DATE=$(date)

if [ $ID -ne 0 ]
then 
    echo "ERROR : You are a root user"
    exit 1
else
    echo "you are root user"
fi

yum install git -y

if [ $? -ne 0 ]
then 
    echo "ERROR"
    exit 1
else
    echo "installation is successful"
fi



 