#!/bin/bash

ID=$(id -u)
TIME=$(date +%F-%H-%M)
LOG_FILE="/tmp/$0-$TIME"
R="\e[31m"
G="\e[32m"
Y="\e[33m"
N="\e[0m"

validate(){
    if [ $1 -ne 0 ]
    then 
        echo -e " $R failed to  $2  $N"
    else
        echo -e " $2 ..  $G is success $N"
    fi
}

if [ $ID -ne 0 ]
then 
    echo -e "$R error : you are not a root user $N"
    exit 1
else
    echo -e "$G you are root user $N"
fi
 
cp mongo.repo /etc/yum.repos.d/mongo.repo &>> $LOG_FILE

validate $? "copied mongo repo"

dnf install mongodb-org -y &>> $LOG_FILE

validate $? "installation of mongodb"

systemctl enable mongod &>> $LOG_FILE

validate $? "enabling mongodb" 

systemctl start mongod &>> $LOG_FILE

validate $? "starting mongodb" 

sed -i 's/127.0.0.1/0.0.0.0/g' /etc/mongod.conf &>> $LOG_FILE

validate $? "editing remotely "

systemctl restart mongod &>> $LOG_FILE

validate $? "restarting mongodb"





