#!/bin/bash

ID=$(id -u)
TIME=$(date +%F-%H-%M)
LOG_FILE="/tmp/$0-$TIME"
R="\e[31m"
G="\e[32m"
Y="\e[33m"
N="\e[0m"

validate(){
    if [ $1 -ne 0 ]
    then 
        echo -e " $2 ..  $R is failed $N"
    else
        echo -e " $2 ..  $G is success $N"
    fi
}

if [ $ID -ne 0 ]
then 
    echo -e "$R error : you are not a root user $N"
    exit 1
else
    echo -e "$G you are root user $N"
fi

dnf install nginx -y &>> $LOG_FILE

validate $? "installation of nginx"

systemctl enable nginx &>> $LOG_FILE

validate $? "enabling the  nginx"

systemctl start nginx &>> $LOG_FILE

validate $? "starting the nginx"

http://<public-IP>:80 &>> $LOG_FILE

rm -rf /usr/share/nginx/html/*

curl -o /tmp/web.zip https://roboshop-builds.s3.amazonaws.com/web.zip

cd /usr/share/nginx/html

unzip /tmp/web.zip

cp /home/centos/11032024_repo/roboshop.conf /etc/nginx/default.d/roboshop.conf 

systemctl restrart nginx &>> $LOG_FILE

validate $? "restarting the nginx"